"""add item_type one_liner full_text to news_items

Revision ID: f0000a0ba4ee
Revises: 878485a6cf3a
Create Date: 2026-06-22 12:40:21.534240

"""
from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision = 'f0000a0ba4ee'
down_revision = '878485a6cf3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('one_liner', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('full_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('item_type', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_column('item_type')
        batch_op.drop_column('full_text')
        batch_op.drop_column('one_liner')

    # ### end Alembic commands ###
